---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: nginx.cluster.local
    http:
      paths:
      - path: /
        backend:
          service:
            name: service-nginx
            port:
              number: 80